### ISSUE TITLE
Database update

### ISSUE THREAD

**Issue by larnacoeur** [bmwcarit/barefoot#15]
Hi, I'm wondering if there is more clever way to update Barefoot's PSQL database other than simple dropping it and reimport all data again. I'd really appreciate every tip in that matter.

Thank you in advance

**Comment by smattheis** [comment]
What do you exactly mean by updating the PSQL database? If you mean (1) doing software updates of the PostgreSQL/PostGIS database, it's trivial - do it in the container; (2) some OSM data, it depends; (3) the map data of Barefoot without server down-time, it's getting tough.

I assume, you mean (3):

The bad news is that there is no more clever way at the moment and there isn't any in a short-term perspective.

The good news is that I tried some things on that in the past, which may give you some little tip but still mean lots of implementation to do:

1. One simple strategy was that I asked the people of osm2po if it's possible with their library, but they said it's too complicated or even impossible.
2. A student of mine recently experimented a little bit and succeeded on getting the diffs of OSM dumps and import it into the database with Osmosis. So that's okay and not complicated, but it's only the first step of lots of steps to get the routing map and the in-memory map of Barefoot updated.

All in all, it's a tough problem and lots of work, but I think it's feasible. An important aspect is that AFAIK there isn't any OSS project that can do that. Otherwise, I would use it and integrate it right away into Barefoot. (Let me know if you know any such project.) If you decide to take the challenge, I would be happy to give you as much support as I can.

**Comment by larnacoeur** [comment]
Thank you for explaination. I want to write some kind of script which will update my OSM database to latest version, let's say every 1-2 months with as little server downtime as possible. 

OT: I imported Europe extract yesterday and I encountered problems in starting Barefoot, either it hangs at RoadMap: inserted ... , or throws OutOfMemory exception. I saw the other issue related to that but didn't find a solution there.

**Comment by smattheis** [comment]
I see the following options:

1. With the current implementation, you could do the following: Set up a second Docker container with an updated map data and start a second instance of Barefoot's stand-alone server reading that map data. To switch between instances, you could have a simple frontend server that is capable to swtich between both in few or less than seconds. In general, the less downtime you want the more infrastructure you need.
2. If you want to have a single stand-alone server running and updating the in-memory map without down-time and with minimal infrastructure, you need (1) Barefoot to handle diffsets of the routing map and (2) you need to produce these diffsets with the Python map tools. Both requires significant extensions of the source code since this feature is just not implemented, as described in my previous post.

OT: I need more details of the problem to be able to help you out.

**Comment by larnacoeur** [comment]
I understand, I'll probably go with option 1. 

OT: I installed Barefoot on my new server machine (CPU: E3 1230V5, RAM: 32GB, HDD: 8TB), imported Europe extract and tried to run map matching server and got OutOfMemory exception so I retried a few times with different command parameters (-Xmx30g, -Xmx32g, -Xmx30g -Xms30g) and every time I got either OutOfMemoryError: GC overhead exceeded or OutOfMemoryException java heap space.. In the other issue you said that you successfully imported Europe on 32GB machine so maybe you can point me out what values are you tried. 

Thank you for your support

**Comment by smattheis** [comment]
To be honest, I would just try with a -Xmx64g ... If you have a swap partition, it will work but will probably have a performance impact. The question is then, what kind of caching strategy is better ...  or should you shrink your map size. My test is quite some time in the past and the amount of OSM data increased enormously. So maybe it's just exceeding the capacity now?

**Comment by smattheis** [comment]
I'm closing this because it has been inactive for a long time. If there still a problem or a new problem, please create a new issue.
