### ISSUE TITLE
Performance and WGS84

### ISSUE THREAD

**Issue by oldrev** [bmwcarit/barefoot#2]
Hello:

This project is just awesome! You author(s) and contributors did a great job, it really helps me a lot.

I found Barefoot is slow while I using real world taxi GPS data: it took about 4 seconds to match 240 GPS samples in my laptop(CPU: i7-2650M, RAM: 8GB).

After profiling with JProfiler, the function Geography.distance() seems to be executed so much times that made it to be a performance bottle-neck.

So my question is: can I use a planar CRS like EPSG:3857 instead of WGS84 to accelerate the distance computing function?

Cheers!

**Comment by smattheis** [comment]
Thanks for the feedback! I can't really reproduce the situation why or where Geography.distance() is called that often. Could you please send me some more details, maybe the stack trace of the function call that occurs most often? (Please note to not profile the import of the map which of course calculates distances of every road.) I added some notes on performance tuning which I can later reuse for the documentation.

#### Sample data-dependent performance tuning
The map matching performance mostly depends on the routing workload as there are many possible routes to be determined to find the best matching positions on the map and routes between them.

##### Sampling interval & route distances
If trace data is recorded with large sampling intervals (low sampling rate), e.g. 60 second intervals or more, it induces long distances between measured positions and induces naturally a high routing workload. However, there is a performance parameter that prevents a certain worst case scenario:
If there is no route between consecutive position candidates, a router would need to search the full map - which may be a complete continent - to come to the conclusion that there is no route. At this point, one can configure the router by setting __matcherMaxDistance__ to stop searching after a certain distance/depth for coming to the conclusion that there is no route. This can be exploited if there is some more knowledge on the data:
* If sampling intervals are small, e.g. 10 second intervals or less, __matcherMaxDistance__ can be set to e.g. 1,000 meters. (For example, given that an object moves with a maximum speed of 200km/h and its trace is sampled in intervals of 10 seconds, maximum distance traveled in that time is 555 meters.)
* If sampling intervals are large, e.g. 180 second intervals or more, __matcherMaxDistance__ must be set to e.g. 15,000 meters. (In the same example, a sampling interval of 180 seconds induces a maximum distance of 10,000 meters to be traveled in that time.)

_Note:_ There is a mechanism implemented for automatically adopting the maximum search distance based on sample interval but, for good reason, it is extremely pessimistic assuming a maximum speed of 360km/h. Hence, a better knowledge of the data enables better performance tuning.

##### Measurement errors & number of matching candidates
The routing workload also depends on the number of matching candidates to be considered for each position measurement. Standard GPS traces have large measurement errors, especially in urban areas or at places like tunnels, which requires to consider matching candidates in a radius of 200 meters around the measured position to provide robust map matching. If there is some better confidence on the accuracy of position measurements, one could lower the value of parameter __matcherMaxRadius__ to consider matching candidates in a radius of e.g. only 100 meters.

**Comment by oldrev** [comment]
Hello, sorry for my toooo late response.

In my project domain, we tried to use Barefoot for GPS offline matching which limited in single city map with an amount of GPS data (about 4,000 cars, 23 millions records per day).

I am not a GIS expert, but I found somehow the function ST_Distance in PostGIS with CRS EPSG:3857 is much faster than WGS84. The reason I assumed the reason is because the EPSG:3858 is a planar CRS that comes with lesser algorithmic complexity.

At this very moment I am trying to port Barefoot from WGS84 to 3857, wish me luck :)

Anyway, I really appreciated for your performance tuning notes. 

Cheers!

**Comment by smattheis** [comment]
That's very interesting, would be nice if you could keep me informed about your porting and feel free to contribute.

To me it's not yet clear if the distance calculation is really the bottleneck!

To the best of my knowledge, performance of map matching is limited by the routing (usually about 80 - 90% of the workload) which doesn't - or shouldn't - require extensive distance calculations. As said before, distance calculation is done on the import and only once per road. Additionally, routing is already parallelized with a work-stealing scheduler giving, at least for the routing workload, an almost linear speed-up.

A performance bottleneck with respect to geographic/geometric operations may be induced by the projection of a point to line (see intercept function) which uses Gnomonic projection that has been ported from Charles Karney's GeographicLib. Here, using EPSG:3857 projection may be indeed more efficient. The crucial point is that a large number of projections of a point to a polyline requires an even larger amount of invocations of the intercept opertaion, no matter which projection we use. A single intercept invocation with WGS-84 takes in my profiling (note that instrumentation of profiling decreases performance additionally) takes no more than 200 microseconds and a distance operation no more than 26 microseconds. The parallel execution of the plain amount of intercept invocations may, however, be the key to improve performance significantly.

I'm telling you that because I would like to avoid that you tune performance where it doesn't give you a significant performance speed-up. However, maybe I'm wrong and you are right. Anyways, I wish you good luck! :)

**Comment by smattheis** [comment]
Is this still an issue? I would close it otherwise.
