### ISSUE TITLE
road-types.json- add track tag

### ISSUE THREAD

**Issue by larnacoeur** [bmwcarit/barefoot#29]
Hi, I want to include track highway tag into my database. Is adding:

```json
{
    "name":"track",
    "id":116,
    "priority":5,
    "maxspeed":50
}
```

enough? How much, do you think, it will affect the import time?

**Comment by smattheis** [comment]
Yes, this should be enough. Make sure to rebuild the database from scratch and delete bfmap files in your working directory.
Since tracks are quite frequent, there will be definitely an impact notable. You can compare it yourself: Tag value `primary` makes about 2% of all ways (http://wiki.openstreetmap.org/wiki/Tag:highway%3Dprimary), whereas `track` makes about 12% (http://wiki.openstreetmap.org/wiki/Tag:highway%3Dtrack). Also note that `unclassified`makes approximately 10% of all ways (http://wiki.openstreetmap.org/wiki/Tag:highway%3Dunclassified) and is a similar type of roads as `track`.
