### ISSUE TITLE
Explanation of server.properties

### ISSUE THREAD

**Issue by nik-ffm** [bmwcarit/barefoot#3]
I am unsure regarding the meaning of some settings in the server.properties. I tried to annotate them with my understanding. If I am wrong, it would be great to become corrected.

```portNumber=1234
# The maximum time is the time after which the work is canceled. But what is the difference between the maximum request and the maximum response time? 
maxRequestTime=30000
maxResponseTime=300000
# Amount of concurrent Connection which is allowed
maxConnectionCount=20
# When do I need to change this number? Does it depend on my hardware, my usage scenario etc.?
numExecutorThreads=40
# The maximum distance between to points. Unit is meter?
matcherMaxDistance=50
# The search radius? Unit is meter?
matcherMaxRadius=50
# Whether every or only every x-th point should be processed
matcherMinInterval=1
# The minimum distance which should lie between two points. Unit is meter?
matcherMinDistance=0
# When do I need to change this number? For maximum performance should it be equal to the amount of cores I have?
matcherNumThreads=8```

**Comment by smattheis** [comment]
First reference should be the Manual page: https://github.com/bmwcarit/barefoot/blob/master/MANUAL.md#server-settings
Some remarks:
- The maximum request time is the time that the server waits between accepting a connection from a client and receiving the request message. If the server does not receive a request message within that time, it closes the connection - giving other clients the chance to connect.
- The maximum response time is the time that the server tries to produce the map matching result. (A request that includes non-standard or faulty data that would take "forever", it would block the map matching server.) If this time limit is exceeded, the map matching server stops processing and returns a timeout message.
- The number of executor threads (name is - for historic reason - a little misleading and should be refactored) is the number of concurrent threads handling requests/responses. Since these threads block frequently until some processing is finished, the number of threads should be relatively high.

**Comment by nik-ffm** [comment]
Thank you very much, I wasn't aware of that part of documentation. I would appreciate a comment referencing the mentioned documentation as comment in the config file.
