### ISSUE TITLE
Problem matching bus/footwalk/bicycle traces

### ISSUE THREAD

**Issue by aggour211** [bmwcarit/barefoot#74]
Hello there,

We have used Barefoot server on a Docker and it could help me a lot in my academic project. It works fine, except that we seem to have 2 main issues:

Here are the two maps, one from GPS, and the other from the result of Barefoot.

- It does not follow normally the map.
- It seems that you use many map points that are not the same as the one we can find on Open street map. As you can see on the map, many point are on a straight line and we guess it is because they are from a openStreetMap path, but you divide it into subpath (?). 

Our objectif is to cross the Map-Matching Barefoot data result to the OpenStreetMap data to get information of the road such as its address, and ig there is a red light, etc.

As you can see from the raw data of GPS and MapMatcher result, there are latitudes and longitudes which are very precise in the digits (ex: 42.78623487523) and we do not find back the data from OpenStreetMap, in order to cross both data sources.

Can you help us understand what is wrong ?
NOTE: We have been using the default server config.

Best regards,

Issam Aggour

![example](https://user-images.githubusercontent.com/32061704/31034857-22561ece-a566-11e7-8f62-e4f1362fbd2e.png)
![example_mapmatched](https://user-images.githubusercontent.com/32061704/31035102-04edb594-a567-11e7-8229-b97988ab73a6.png)

[After_Mapmatching.txt](https://github.com/bmwcarit/barefoot/files/1345616/After_Mapmatching.txt)
[Raw_Data.txt](https://github.com/bmwcarit/barefoot/files/1345617/Raw_Data.txt)

**Comment by smattheis** [comment]
Could you please provide the input data in the format that you used to produce the matching result? Thanks.

**Comment by aggour211** [comment]
Thank you for you quick answer !

Here is the json file we used as input in this case:
[http://uptobox.com/ufl2wnbe90nz](url)

Best regards,
Issam

**Comment by smattheis** [comment]
It seems that your trace is recorded from a trip by foot or bicycle and the route violates one-way rules that hold for motorized vehicles. Since the matcher/router doesn't know that, it forces the search for legal routes and, hence, provides respective detours.

A quick fix could be to rewrite one-way information in the database, e.g., with:
```bash
sudo docker exec <container> bash -c 'psql -h localhost -U osmuser -d <database> -c "create table bfmap_ways_foot as table bfmap_ways;"'
sudo docker exec <container> bash -c 'psql -h localhost -U osmuser -d <database> -c "update bfmap_ways_foot set reverse=1;"'
```

After that, set the table in `database.properties` to:
```
database.table=bfmap_ways_foot
```
__Note:__ Don't forget to delete the .bfmap file, because it holds the map for motorized vehicles!

After that I get the following result with `matcher.sigma=15` and `matcher.distance.min=5`:

![barefoot_ile-de-france_footpath](https://user-images.githubusercontent.com/7805104/31053598-6ff51518-a6a1-11e7-9a85-93f7dd22b68e.png)

The little detours are from position measurement errors (probably you walked diagonal to the roads across a place or so). I think the matcher can't help here because it's too ambiguous.

**Comment by aggour211** [comment]
Thank you very much for the explanation and fix. But it was not a bicycle, but a bus trip. The bus was going in the opposite direction on a one-way road, as expected by OpenStreetMap data. As you can see on the OpenStreetMap screenshot, for this road, "busway=opposite_lane".
![screen shot 2017-10-01 at 13 01 48](https://user-images.githubusercontent.com/32061704/31054756-1fc8d552-a6ba-11e7-95f2-99bd2bb4fbf1.png)

**Comment by smattheis** [comment]
I see, to fix such specific roads you can correct the particular road in the database respectively:
``` bash
sudo docker exec <container> bash -c 'psql -h localhost -U osmuser -d <database> -c "update bfmap_ways_foot set reverse=1 where osm_id=<osm-id>;"'
```
